config/routes.rb
Careerlife::Application.routes.draw do
  resources :careers do
    collection do
      get 'new_career_detail'
    end
  end

  root 'welcome#index'
end

app/models/career.rb
class Career < ActiveRecord::Base

  has_many :career_details
  accepts_nested_attributes_for :career_details, :allow_destroy => true

  def full_name
    self.last_name.to_s + self.first_name.to_s
  end

  def gender_name
    case self.gender.upcase
    when 'M'
      '男性'
    when 'F'
      '女性'
    end
  end

end

app/models/career_condition.rb
# coding: UTF-8

class CareerCondition < Daddy::Model
end

app/models/career_const.rb
# coding: UTF-8

module CareerConst

  GENDERS = {
    GENDER_FEMALE = 'F' => '女性',
    GENDER_MAIL = 'M' => '男性'
  }

end

app/models/career_detail.rb
# coding: UTF-8

class CareerDetail < ActiveRecord::Base
  validates :project_name, :presence => true
  validates :role, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  include UserConst

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :last_name, :presence => true, :on => :update
  validates :first_name, :presence => true, :on => :update

  has_one :career

  def full_name
    self.last_name.to_s + self.first_name.to_s
  end

  def gender_name
    GENDERS[self.gender]
  end

  def age
    return nil unless self.birthday
    
    now = Time.now.utc.to_date
    now.year - self.birthday.year - ((now.month > self.birthday.month || (now.month == self.birthday.month && now.day >= self.birthday.day)) ? 0 : 1)
  end
end

app/models/user_const.rb
# coding: UTF-8

module UserConst

  GENDERS = {
    GENDER_FEMALE = 'F' => '女性',
    GENDER_MAIL = 'M' => '男性'
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController

  def index
    @careers = Career.not_deleted
  end

  def show
    @career = Career.find(params[:id])
  end

  def new
    @career = Career.new
  end

  def new_career_detail
    @career_detail = CareerDetail.new
    render :partial => 'career_detail_fields', :locals => {:career_detail => @career_detail, :index => params[:index]}
  end

  def create
    @career = Career.new(career_params)

    begin
      @career.transaction do
        @career.save!
      end

      redirect_to :action => 'show', :id => @career.id, :notice => t('messages.created', :name => Career.model_name.human)

    rescue ActiveRecord::RecordInvalid => e
      render :new
    end
  end

  def edit
    @career = Career.find(params[:id])
  end

  def update
    @career = Career.find(params[:id])
    @career.attributes = career_params

    begin
      @career.transaction do
        @career.save!
      end

      redirect_to :action => 'show', :id => @career.id, :notice => t('messages.updated', :name => Career.model_name.human)

    rescue ActiveRecord::RecordInvalid => e
      render :edit
    end
  end

  def destroy
    @career = Career.find(params[:id])

    @career.transaction do
      @career.destroy_logically!
    end

    redirect_to :action => 'index', :notice => t('messages.deleted', :name => Career.model_name.human)
  end

  private

  def career_params
    params.require(:career).permit!
  end

end

app/controllers/profiles_controller.rb
# coding: UTF-8

class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def index
    redirect_to :action => 'show', :id => current_user.id
  end

  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    
    begin
      @user.update_attributes!(params[:user])
      flash[:notice] = t('messages.updated', :name => User.model_name.human)
      redirect_to :action => 'show', :id => @user.id
      
    rescue ActiveRecord::RecordInvalid => e
      render :action => 'edit', :id => @user.id
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Daddy::Helpers::HtmlHelper

  def render_errors(model)
    render :partial => 'common/errors', :locals => {:model => model}
  end

  def render_notices
    render :partial => 'common/notices'
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/careers/_career_detail_fields.html.erb
<%= fields_for 'career[career_details_attributes]', career_detail, :index => index do |f| %>
  <tr>
    <td><%= f.text_field :project_name %></td>
    <td><%= f.text_field :role %></td>
    <td><%= f.text_field :start_date, :class => 'datepicker' %></td>
    <td><%= f.text_field :end_date, :class => 'datepicker' %></td>
    <td>
      <%= f.hidden_field :id %>
      <%= f.hidden_field :_destroy %>
      <a href="#" onclick="delete_career_detail(this); return false;">削除</a>
      <script>
        $(document).ready(function() {
          $('.datepicker').css({'width': '6em', 'text-align': 'center'}).datepicker();
        });

        function delete_career_detail(link) {
          var tr = $(link).closest('tr');
          tr.find('input[name*="_destroy"]').val(true);
          tr.hide();
        }
      </script>
    </td>
  </tr>
<% end %>

app/views/careers/_career_details_fields.html.erb
<div class="career_details">
  <table class="solid">
    <tr>
      <th><%= CareerDetail.human_attribute_name :project_name %></th>
      <th><%= CareerDetail.human_attribute_name :role %></th>
      <th><%= CareerDetail.human_attribute_name :start_date %></th>
      <th><%= CareerDetail.human_attribute_name :end_date %></th>
      <th></th>
    </tr>

    <% @career.career_details.each_with_index do |cd, i| %>
      <%= render 'career_detail_fields', :career_detail => cd, :index => i %>
    <% end %>

    <tr>
      <td colspan="5">
        <a id="new_career_detail_link" href="#">経歴を追加</a>
        <script>
          $(document).ready(function() {
            var link = $('#new_career_detail_link');
            link.click(function() {
              var index = link.closest('table').find('tr').length;

              $.get('<%= url_for :action => 'new_career_detail' %>', {index: index, format: 'html'},
                function(data) {
                  link.closest('tr').before(data);
                });
              });
          });
        </script>
      </td>
    </tr>
  </table>
</div>

app/views/careers/_form.html.erb
<%= form_for @career do |f| %>
  <% if @career.errors.any? %>
    <div class="errors">
      <ul>
        <% @career.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <th><%= f.label :last_name %></th>
      <td><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <th><%= f.label :first_name %></th>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <th><%= f.label :birthday %></th>
      <td><%= f.text_field :birthday %></td>
    </tr>
    <tr>
      <th><%= f.label :gender %></th>
      <td>
        <label><%= f.radio_button :gender, 'M' %> 男性</label>
        <label><%= f.radio_button :gender, 'F' %> 女性</label>
    </tr>
    <tr>
      <th><%= f.label :introduction %></th>
      <td><%= f.text_area :introduction %></td>
    </tr>
  </table>

  <table class="career_details">
    <tr>
      <th><%= CareerDetail.human_attribute_name :project_name %></th>
      <th><%= CareerDetail.human_attribute_name :start_date %></th>
      <th><%= CareerDetail.human_attribute_name :end_date %></th>
      <th></th>
    </tr>

    <% @career.career_details.each_with_index do |cd, i| %>
      <%= render 'career_detail_fields', :career_detail => cd, :index => i %>
    <% end %>

    <tr>
      <td colspan="3">
        <a id="new_career_detail_link" href="#">経歴を追加</a>
        <script>
          $(document).ready(function() {
            var link = $('#new_career_detail_link');
            link.click(function() {
              var index = link.closest('table').find('tr').length;

              $.get('<%= url_for :action => 'new_career_detail' %>', {index: index, format: 'html'},
                function(data) {
                  link.closest('tr').before(data);
                });
              });
          });
        </script>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/careers/_show_career_details.html.erb
<div class="career_details">
  <table class="solid">
    <tr>
      <th><%= CareerDetail.human_attribute_name :project_name %></th>
      <th><%= CareerDetail.human_attribute_name :role %></th>
      <th><%= CareerDetail.human_attribute_name :start_date %></th>
      <th><%= CareerDetail.human_attribute_name :end_date %></th>
    </tr>

    <% @career.career_details.each do |cd| %>
      <tr>
        <td><%= cd.project_name %></td>
        <td><%= cd.role %></td>
        <td><%= cd.start_date %></td>
        <td><%= cd.end_date %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/careers/edit.html.erb
<h1>キャリアの編集</h1>

<div class="actions">
  <%= link_to '一覧', careers_path %>
  <%= link_to '参照', career_path(@career) %>
</div>

<%= render 'form' %>

app/views/careers/index.html.erb
<h1>キャリア一覧</h1>

<div class="actions">
  <%= link_to '追加', new_career_path %>
</div>

<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th><%= Career.human_attribute_name :last_name %></th>
    <th><%= Career.human_attribute_name :first_name %></th>
    <th><%= Career.human_attribute_name :birthday %></th>
    <th><%= Career.human_attribute_name :gender %></th>
    <th colspan="2"></th>
  </tr>
  
  <% @careers.each do |c| %>
    <tr>
      <td><%= c.last_name %></td>
      <td><%= c.first_name %></td>
      <td><%= c.birthday %></td>
      <td><%= c.gender %></td>
      <td>
        <%= link_to '編集', edit_career_path(c) %>
      </td>
      <td>
        <%= link_to '削除', career_path(c), :method => 'delete', data: { confirm: "#{c.full_name} を削除します。よろしいですか？" } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/careers/new.html.erb
<h1>キャリアの追加</h1>

<div class="actions">
  <%= link_to '一覧', careers_path %>
</div>

<%= render 'form' %>

app/views/careers/show.html.erb
<div class="actions">
  <%= link_to '一覧', careers_path %>
  <%= link_to '編集', edit_career_path(@career) %>
  <%= link_to '削除', career_path(@career), :method => 'delete', data: {confirm: '削除します。よろしいですか？'} %>
</div>

<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th><%= Career.human_attribute_name :last_name %></th>
    <td><%= @career.last_name %></td>
  </tr>
  <tr>
    <th><%= Career.human_attribute_name :first_name %></th>
    <td><%= @career.first_name %></td>
  </tr>
  <tr>
    <th><%= Career.human_attribute_name :birthday %></th>
    <td><%= @career.birthday %></td>
  </tr>
  <tr>
    <th><%= Career.human_attribute_name :gender %></th>
    <td><%= @career.gender %></td>
  </tr>
  <tr>
    <th><%= Career.human_attribute_name :introduction %></th>
    <td><%= @career.introduction %></td>
  </tr>
  <tr>
    <th><%= Career.human_attribute_name :created_at %></th>
    <td><%= @career.created_at %></td>
  </tr>
  <tr>
    <th><%= Career.human_attribute_name :updated_at %></th>
    <td><%= @career.updated_at %></td>
  </tr>
</table>

<%= render 'show_career_details' %>

app/views/common/_errors.html.erb
<% if model.errors.any? %>
  <div class="errors">
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/common/_header.html.erb
<div>
  <%= link_to 'TOP', root_path %>
  |
  <%= link_to 'キャリアを登録', careers_path %>
</div>

app/views/common/_notices.html.erb
<% if notice.present? %>
  <div class="notices">
    <ul>
      <li><%= notice %></li>
    </ul>
  </div>
<% end %>

app/views/common/_profiles_menu.html.erb
<ul>
  <li>
    <%= link_to '基本情報', profiles_path %>
  </li>
  <li>
    <%= link_to 'キャリア', careers_path %>
  </li>
</ul>

<script>
  $(document).ready(function() {
    $('.profiles .menu ul li').hover(function() {
      $(this).css('cursor', 'pointer');
    })
    .click(function() {
      document.location.href = $(this).find('a').attr('href');
     });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Career x Life</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wapper">
    <%= render 'common/header' %>
    <% if content_for?(:content) %>
      <%= yield :content %>
    <% else %>
      <%= yield %>
    <% end %>
  </div>
</body>
</html>

app/views/layouts/profiles.html.erb
<% content_for :content do %>
  <div class="profiles">
    <div class="menu">
      <%= render 'common/profiles_menu' %>
    </div>
    <div class="content">
      <%= yield %>
    </div>
  </div>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/profiles/_form.html.erb
<div class="profile">
  <script>
    $(document).ready(function() {
      $('.datepicker').css({'width': '6em', 'text-align': 'center'}).datepicker();
    });
  </script>

  <%= form_for(@user, :url => {:action => 'update', :id => @user.id}, :method => 'put') do |f| %>
    <%= render_errors @user %>
    <div class="actions">
      <%= f.submit %>
    </div>
    <br />
    <div>
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div>
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :birthday %><br />
      <%= f.text_field :birthday, :class => 'datepicker' %>
    </div>
    <div>
      <%= f.label :gender %><br />
      <%= f.select :gender, User::GENDERS.invert %>
    </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<h1>プロフィールの編集</h1>

<%= render 'form' %>

<%= link_to '参照', profile_path(@user) %>

app/views/profiles/show.html.erb
<%= render_notices %>

<p>
  <b><%= User.human_attribute_name :last_name %>:</b>
  <%= @user.last_name %>
</p>

<p>
  <b><%= User.human_attribute_name :first_name %>:</b>
  <%= @user.first_name %>
</p>

<p>
  <b><%= User.human_attribute_name :birthday %>:</b>
  <%= @user.birthday %>
</p>

<p>
  <b><%= User.human_attribute_name :gender %>:</b>
  <%= @user.gender_name %>
</p>

<%= link_to '編集', edit_profile_path(@user) %>

app/views/top/_search.html.erb
<div class="search">
  <%= form_for @condition, :url => {:action => 'index'}, :method => 'get' do |f| %>
    <span><label for="career_condition_keyword">氏名</label>：<%= f.text_field :keyword, :size => 16 %></span>
    <span><label for="career_condition_gender">性別</label>：<%= f.select :gender, User::GENDERS.invert, :include_blank => true %></span>
    <%= f.submit '検索する' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>ようこそ！</h1>